### ISSUE TITLE
Do a non-beta pre-release

### ISSUE THREAD

**Issue by antichris** [marc-mabe/php-enum-polyfill#4]
As far as I can tell, this has been sitting at `v1.0.0-beta1` for the past 4 months with only 3 unreleased commits since then.

Would you mind tagging a release that would not require dependent Composer projects to nerf down their minimum stability constraint? Like a semver major-zero (`v0.y.z`), if you expect to have many breaking changes still coming, e.g. `v0.1.0` or something?

**Comment by marc-mabe** [comment]
Just released RC1

Now emulated case constants needs to be private to make sure `MyEnum::MYCASE` will not be used directly.
Please use `MyEnum::MYCASE()` instead.

If everything works as expected I'll release the first stable version soon.

**Comment by antichris** [comment]
> emulated case constants needs to be private

PHPStan [does not like this](https://phpstan.org/r/79ec9a7b-6a9c-4a1c-89c4-a4611c1ec16b). Using `protected` instead [does seem fine](https://phpstan.org/r/06399ef0-4431-4ee0-b1d8-5bca5c34f2d9) though.

Making those constants `private` also kind of does not fit well with the OOP's access modifier model, where no one else but the class itself (or its instances) are allowed to touch their `private`s. I get that this is a very special case, we're already hacking around the language flaws through the magic of reflection here, but using `protected` for this makes more sense to me.

> If everything works as expected I'll release the first stable version soon.

So, no `0.1.0` until then?
Any projections on the scale of that "soon" — months, weeks, days, hours?

**Comment by marc-mabe** [comment]
> > emulated case constants needs to be private
> 
> PHPStan [does not like this](https://phpstan.org/r/79ec9a7b-6a9c-4a1c-89c4-a4611c1ec16b). Using `protected` instead [does seem fine](https://phpstan.org/r/06399ef0-4431-4ee0-b1d8-5bca5c34f2d9) though.
> 
> Making those constants `private` also kind of does not fit well with the OOP's access modifier model, where no one else but the class itself (or its instances) are allowed to touch their `private`s. I get that this is a very special case, we're already hacking around the language flaws through the magic of reflection here, but using `protected` for this makes more sense to me.

I forgot to mention - there is a PHPStan extension included to avoid this issue:
* https://github.com/marc-mabe/php-enum-cl/blob/main/phpstan.neon.dist#L9-L13
* https://phpstan.org/developing-extensions/always-used-class-constants

> 
> > If everything works as expected I'll release the first stable version soon.
> 
> So, no `0.1.0` until then? Any projections on the scale of that "soon" — months, weeks, days, hours?

I'll include this lib myself into another project this week as test run, too.

**Comment by antichris** [comment]
> there is a PHPStan extension included to avoid this issue

Alright, that works too. Although simply defining the constants as `protected` still seems lower complexity than setting up a PHPStan extension (which would not work for an online check, for example), I can also see the point in formally avoiding `protected` members in a `final` class.
At the end of the day, there's nothing to preclude me or anyone else defining our constants `protected` and foregoing that whole extension business (a word on this in the documentation could be useful though).

> I'll include this lib myself into another project this week as test run, too.

Good luck then, I'll be looking forward to a release.
A major-zero release would've been cool (as in, immediately useful to me too), but if the time frame of a stable one is a week or two, sure, I can wait.

**Comment by marc-mabe** [comment]
@antichris 1.0.0-rc3 works for me in another project - if it works fine for you too I'll create a first stable version

**Comment by antichris** [comment]
@marc-mabe Looks fine to me.

But you shouldn't be waiting for positive feedback to do releases — this is precisely the reason why I initially suggested that you start releasing major-zero versions, so you can iterate on feedback (issue reports, if any even happen), freely do new releases as soon as you have something ready, and only settle down on a full 1.0.0 when it does indeed look stable. PHPStan, for example, was in major-zero mode for 6 years, but it didn't stop everyone from using it.

Also, I still strongly believe that it would be better for emulated case constants to be `protected` canonically, as

- `private` implies that it is something that only the concrete class alone has access to, while protected members are usually accessible by the members of the inheritance tree — typically downstream, but, as a counterexample, `protected` abstract methods, even though only ever implemented by an inheriting class, are called by the defining class (which is upstream from the implementation "values").
- `protected` is less of a hassle; both [Psalm](https://psalm.dev/r/9a4eac91aa) and [PHPStan](https://phpstan.org/r/c249d078-453f-4586-aaed-c9e718258211) are perfectly fine with that, right out of the box, without going and messing with any configs and/or plugins.

Requiring your users to reconfigure something about their environment is a completely unnecessary extra step that might even have a deterring effect.

**Comment by marc-mabe** [comment]
@antichris 

About the releases I don't like shipping 0.x releases for  projects like this. Either It's considered stable or not (beta/rc) and I don't see why tricking package managers with a 0.x releases.

About private vs protected constants: There is no real difference in case of final classes but I see where you are coming form. Actually PHPStan just supports this kind of detection and I think at some point they will detect the same with protected constants on final classes as well. Anyway, as it seems to help reducing necessary configuration for static code analyzers and IDE's I'll change it to use protected constants but I'll keep the PHPStan extension as well.

**Comment by marc-mabe** [comment]
1.0 is released :tada:
